#!/usr/bin/env bash
set -euo pipefail
# ─────────────────────────────────────────────────────────────────────────────
# contract-survey: Auto-generate a baseline security-survey document for the
# tier-1 gameplay contracts.
#
# Usage:
#   ./tools/contract-survey/survey.sh          # prints Markdown to stdout
#   ./tools/contract-survey/survey.sh --write  # overwrites docs/audits/contract-survey-2026.md
# ─────────────────────────────────────────────────────────────────────────────

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CONTRACTS_DIR="${REPO_ROOT}/contracts"
OUTPUT_FILE="${REPO_ROOT}/docs/audits/contract-survey-2026.md"

# Tier-1 modules that must appear in the survey.
TIER1_CONTRACTS=(
  puzzle_verification
  referral
  insurance
  puzzle_dao
  flash_loan
  token_swap
)

# ── helpers ──────────────────────────────────────────────────────────────────

extract_pub_fns() {
  local file="$1"
  grep -oE 'pub fn [a-z_]+' "$file" 2>/dev/null | sed 's/pub fn //' | sort -u || true
}

extract_events() {
  local file="$1"
  grep -oE 'env\.events\(\)\.publish\(' "$file" 2>/dev/null | wc -l | tr -d ' ' || echo 0
}

extract_event_topics() {
  local file="$1"
  grep -oP 'Symbol::new\(&env,\s*"[^"]+"\)' "$file" 2>/dev/null \
    | sed 's/Symbol::new(&env, "//; s/")//' \
    | sort -u || true
}

count_storage_keys() {
  local file="$1"
  grep -cE 'DataKey::' "$file" 2>/dev/null || echo 0
}

has_require_auth() {
  local file="$1"
  local count
  count=$(grep -cE '\.require_auth\(\)' "$file" 2>/dev/null || echo 0)
  if [ "$count" -gt 0 ]; then
    echo "Yes (${count} call-sites)"
  else
    echo "No"
  fi
}

has_pause_guard() {
  local file="$1"
  if grep -qE 'assert_not_paused|\.paused' "$file" 2>/dev/null; then
    echo "Yes"
  else
    echo "No"
  fi
}

has_reentrancy_guard() {
  local file="$1"
  if grep -qE 'assert_not_reentrant|ReentrancyGuard|reentrancy' "$file" 2>/dev/null; then
    echo "Yes"
  else
    echo "No"
  fi
}

uses_checked_arithmetic() {
  local file="$1"
  if grep -qE 'checked_|\.checked_add|\.checked_sub|\.checked_mul|\.checked_div|\.overflowing' "$file" 2>/dev/null; then
    echo "Yes"
  else
    echo "No (uses wrapping arithmetic)"
  fi
}

error_handling_style() {
  local file="$1"
  if grep -qE '-> Result<' "$file" 2>/dev/null; then
    echo "Result<T, E>"
  elif grep -qE '#\[should_panic\]|panic!\(' "$file" 2>/dev/null; then
    echo "panic!-based"
  else
    echo "Unknown"
  fi
}

# ── main ─────────────────────────────────────────────────────────────────────

generate_markdown() {
  cat <<'HEADER'
# Contract Survey 2026

> Auto-generated by `tools/contract-survey/survey.sh` — do not edit by hand.
> Regenerate: `./tools/contract-survey/survey.sh --write`

Per-contract feature / audit-status snapshot for all **tier-1 gameplay modules**.

---

HEADER

  for crate in "${TIER1_CONTRACTS[@]}"; do
    src="${CONTRACTS_DIR}/${crate}/src/lib.rs"
    if [ ! -f "$src" ]; then
      echo "## ${crate}"
      echo ""
      echo "> ⚠ Source file not found: \`contracts/${crate}/src/lib.rs\`"
      echo ""
      continue
    fi

    pub_fns=$(extract_pub_fns "$src")
    pub_count=$(echo "$pub_fns" | grep -c . 2>/dev/null || echo 0)
    event_count=$(extract_events "$src")
    event_topics=$(extract_event_topics "$src")
    storage_keys=$(count_storage_keys "$src")
    auth=$(has_require_auth "$src")
    pause=$(has_pause_guard "$src")
    reentrancy=$(has_reentrancy_guard "$src")
    arithmetic=$(uses_checked_arithmetic "$src")
    error_style=$(error_handling_style "$src")

    cat <<EOF
## ${crate}

| Property | Value |
|---|---|
| Source | \`contracts/${crate}/src/lib.rs\` |
| Public methods | ${pub_count} |
| Events emitted | ${event_count} distinct call-sites |
| Storage keys (DataKey variants) | ${storage_keys} |
| require\_auth guards | ${auth} |
| Pause guard | ${pause} |
| Reentrancy guard | ${reentrancy} |
| Checked arithmetic | ${arithmetic} |
| Error handling style | ${error_style} |

### Public Methods

EOF

    echo "$pub_fns" | while IFS= read -r fn; do
      [ -n "$fn" ] && echo "- \`${fn}\`"
    done

    cat <<EOF

### Events

EOF

    if [ "$event_count" -gt 0 ] && [ -n "$event_topics" ]; then
      echo "$event_topics" | while IFS= read -r topic; do
        [ -n "$topic" ] && echo "- \`${topic}\`"
      done
    else
      echo "- _(none detected)_"
    fi

    echo ""
    echo "---"
    echo ""
  done

  cat <<'FOOTER'
## Notes

- **Checked arithmetic**: The `No (uses wrapping arithmetic)` flag indicates the contract
  relies on default Rust wrapping semantics for integer arithmetic.  This is a known
  risk area; see Issue #22 and Issue #7 for tracked remediation.
- **Error handling**: Contracts currently using `panic!`-based errors are candidates for
  migration to `Result<T, PuzzleError>` (ADR-0005, Issue #32).
- **Reentrancy**: The `referral` contract performs cross-contract token transfers
  without a reentrancy guard; see Issue #16 for tracked mitigation.

### Dependency graph

\`\`\`
puzzle_verification ──depends-on──▶ ADR-0005 (Issue #32)
referral            ──open-issue──▶ Issue #16 (reentrancy mitigation)
insurance           ──open-issue──▶ Issue #22 (checked arithmetic)
flash_loan          ──has-guard───▶ ReentrancyGuard ✓
token_swap          ──audit-status▶ Needs review
puzzle_dao          ──has-pause───▶ Pause guard (implicit)
\`\`\`

### Tier-1 Audit Status Summary

| Contract | Last audited | Open issues | Risk level |
|---|---|---|---|
| puzzle_verification | Not yet | #32 (ADR-0005) | Medium |
| referral | Not yet | #16 (reentrancy) | High |
| insurance | Not yet | #22 (arithmetic) | Medium |
| puzzle_dao | Not yet | #37 (multisig) | Medium |
| flash_loan | Not yet | — | Low |
| token_swap | Not yet | — | Low |
FOOTER
}

# ── entry point ──────────────────────────────────────────────────────────────

if [ "${1:-}" = "--write" ]; then
  mkdir -p "$(dirname "$OUTPUT_FILE")"
  generate_markdown > "$OUTPUT_FILE"
  echo "✅  Survey written to ${OUTPUT_FILE}"
else
  generate_markdown
fi
